#server.port=8222
#spring.application.name=fund-gateway
#spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
#spring.cloud.gateway.discovery.locator.enabled=true
#
#spring.cloud.gateway.routes[0].id=fund-service
#spring.cloud.gateway.routes[0].uri=lb://fund-service
#spring.cloud.gateway.routes[0].predicates= - Path=/*/fund/**

server:
  port: 8222
spring:
  application:
    name: fund-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
      - id: fund_service_route
        uri: lb://fund-service
        predicates:
        - Path=/fund/**