package com.leo.fundservice.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.leo.fundservice.model.FundUser;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

/**
 * 功能描述：基金用户mapper
 * @author leopard
 * @date 2021/05/22
 */
@Mapper
@Component
public interface FundUserMapper extends BaseMapper<FundUser> {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_USER
     *
     * @mbg.generated Sat May 22 17:11:23 GMT+08:00 2021
     */
    @Override
    int insert(FundUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_USER
     *
     * @mbg.generated Sat May 22 17:11:23 GMT+08:00 2021
     */
    int insertSelective(FundUser record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_USER
     *
     * @mbg.generated Sat May 22 17:11:23 GMT+08:00 2021
     */
    int updateByExampleSelective(@Param("record") FundUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND_USER
     *
     * @mbg.generated Sat May 22 17:11:23 GMT+08:00 2021
     */
    int updateByExample(@Param("record") FundUser record);
}